version: '3.9'

services:
  stt-service:
    build: ./stt-service
    container_name: stt-service
    command: ["bash", "-c", "npm install -g pm2 && ./setup_pm2.sh"]

    volumes:
      - ./stt-service:/app
    networks:
      - homeSmart-network
    restart: always  # Asegura que el servicio se reinicie automáticamente si falla
    environment:
      - NODE_ENV=testing

  recording-service:
    build: ./recording-service
    container_name: recording-service
    command: ["node", "main.js"]
    volumes:
      - ./recording-service:/app
    networks:
      - homeSmart-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    command: ["node", "main.js"]
    volumes:
      - ./notification-service:/app
    networks:
      - homeSmart-network

  iot-control-service:
    build: ./iot-control-service
    container_name: iot-control-service
    command: ["node", "main.js"]
    volumes:
      - ./iot-control-service:/app
    networks:
      - homeSmart-network

  user-management-service:
    build: ./user-management-service
    container_name: user-management-service
    command: ["node", "main.js"]
    volumes:
      - ./user-management-service:/app
    networks:
      - homeSmart-network

  orchestration-service:
    build: ./orchestration-service
    container_name: orchestration-service
    command: ["node", "main.js"]
    volumes:
      - ./orchestration-service:/app
    networks:
      - homeSmart-network

  network-monitor:
    build: ./network-monitor
    container_name: network-monitor
    command: ["node", "main.js"]
    volumes:
      - ./network-monitor:/app
    networks:
      - homeSmart-network

networks:
  homeSmart-network:
    driver: bridge
